### ISSUE TITLE
integrate the project a CI tool

### ISSUE THREAD

**Issue by camandel** [SYNwall/SYNwall#25]
It would be nice to have a continuous integration tool for this project.

To do that in my lab I happily use [agola](https://agola.io) but compile and test kernel modules into containers is not safe at all.
So it would be better to use a CI tool based on VMs like [travis](https://travis-ci.org/).
For my SYNwall fork I use travis with this simple configuration:
```
language: c
before_install:
  - sudo apt-get install linux-headers-$(uname -r)
script: make && make test
```
In about 45 seconds it spins up a VM, installs deps, compiles modules, executes tests and then destroys it.

**Comment by cecio** [comment]
That's a great idea! 
Yes, unfortunately containers are not usable for kernel modules testing, but VMs are actually totally usable. 
I'm not an expert with travis by any mean. So what you wrote is just what is needed in terms of configurations for CI with travis? If so I think we can add it to the main package.

**Comment by camandel** [comment]
Yes, just sign-in on travis with your GitHub account, link the project, enable the CI on it and create a `.travis.yml` configuration file into the root of project.

**Comment by cecio** [comment]
Great! I'll try that on my fork then move it on the main. Thanks!

**Comment by cecio** [comment]
OK, done. Looks good!
Thanks a lot for the suggestion.
